version: "3.7"
services:
  mysql:
    image: mysql:8.3
    container_name: bmi-system
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
