// Code generated by mockery v2.20.0. DO NOT EDIT.

package util

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockTimeUtil is an autogenerated mock type for the TimeUtil type
type MockTimeUtil struct {
	mock.Mock
}

type MockTimeUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimeUtil) EXPECT() *MockTimeUtil_Expecter {
	return &MockTimeUtil_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with given fields:
func (_m *MockTimeUtil) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTimeUtil_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTimeUtil_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockTimeUtil_Expecter) Now() *MockTimeUtil_Now_Call {
	return &MockTimeUtil_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockTimeUtil_Now_Call) Run(run func()) *MockTimeUtil_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimeUtil_Now_Call) Return(_a0 time.Time) *MockTimeUtil_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeUtil_Now_Call) RunAndReturn(run func() time.Time) *MockTimeUtil_Now_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockTimeUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTimeUtil creates a new instance of MockTimeUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTimeUtil(t mockConstructorTestingTNewMockTimeUtil) *MockTimeUtil {
	mock := &MockTimeUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
